version: 2.1

jobs:
  process:
    docker:
      - image: cimg/python:3.9  # 使用Python 3.9的CircleCI官方镜像
    environment:
      TZ: Asia/Shanghai
      GIST_PAT: ${GIST_PAT}
      GIST_LINK: ${GIST_LINK}
      CUSTOMIZE_LINK: ${CUSTOMIZE_LINK}
      ENABLE_SPECIAL_PROTOCOLS: ${ENABLE_SPECIAL_PROTOCOLS}
    steps:
      - checkout
      
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - run:
          name: Validate environment variables
          command: |
            if [ -z "$GIST_PAT" ]; then
              echo "Error: environment 'GIST_PAT' cannot be empty"
              exit 1
            fi

            if [ -z "$GIST_LINK" ]; then
              echo "Error: environment 'GIST_LINK' cannot be empty"
              exit 1
            fi

            LINK_PARTS=$(echo "$GIST_LINK" | awk -F'/' 'NF==2 && $1!="" && $2!=""')
            if [ -z "$LINK_PARTS" ]; then
              echo "Error: environment 'GIST_LINK' is not valid, should be 'username/gist_id' format"
              exit 1
            fi

      - run:
          name: Collect data
          command: python -u subscribe/collect.py --all --both --overwrite --skip

      - run:
          name: Print timestamp
          command: date

workflows:
  version: 2
  weekly_collect:
    triggers:
      - schedule:
          cron: "0 0 * * 1"
          filters:
            branches:
              only:
                - main
    jobs:
      - process
